title: Harshini Jawahar
logo: Headshot_pink.jpeg
show_downloads: true
theme: jekyll-theme-dinky
# other themes : Architect, Cayman, Dinky, Hacker, Leap day, Merlot, Midnight, Minima, Minimal, Modernist, Slate, Tactile, Time machine
