title: Harshini Jawahar
logo: /assets/Untitled design.jpeg
show_downloads: true
theme: jekyll-theme-minimal
# other themes : Architect, Cayman, Dinky, Hacker, Leap day, Merlot, Midnight, Minima, Minimal, Modernist, Slate, Tactile, Time machine
