title: Harshini Jawahar
logo: logo: /assets/Untitled%20design.jpeg
show_downloads: true
theme: jekyll-theme-minimal
# other themes : Architect, Cayman, Dinky, Hacker, Leap day, Merlot, Midnight, Minima, Minimal, Modernist, Slate, Tactile, Time machine
