title: Harshini Jawahar
logo: https://github.com/harshini8-10/harshinijawahar.github.io/blob/main/assets/Untitled%20design.jpeg
show_downloads: true
theme: jekyll-theme-minimal
# other themes : Architect, Cayman, Dinky, Hacker, Leap day, Merlot, Midnight, Minima, Minimal, Modernist, Slate, Tactile, Time machine
