title: Harshini Jawahar
logo: Headshot.jpeg
show_downloads: true
theme: jekyll-theme-modernist
# other themes : Architect, Cayman, Dinky, Hacker, Leap day, Merlot, Midnight, Minima, Minimal, Modernist, Slate, Tactile, Time machine
